// Generated by Bisonc++ V5.02.00 on Mon, 25 May 2020 09:14:09 +0200

// $insert class.ih
#include "Parser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them


namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
    enum                        // size to expand the state-stack with when
    {                           // full
        STACK_EXPANSION__ = 10
    };

// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {301, 4}, // 1: start (PROGRAM) ->  PROGRAM VAR END declaration
     {302, 1}, // 2: declaration ->  body
     {302, 4}, // 3: declaration (DATA) ->  DATA DDOT vardeclaration body
     {303, 5}, // 4: vardeclaration (VAR) ->  VAR TYPE INT SEPARATOR vardeclaration
     {303, 5}, // 5: vardeclaration (VAR) ->  VAR TYPE BOOL SEPARATOR vardeclaration
     {303, 4}, // 6: vardeclaration (VAR) ->  VAR TYPE INT END
     {303, 4}, // 7: vardeclaration (VAR) ->  VAR TYPE BOOL END
     {304, 0}, // 8: body ->  <empty>
     {304, 1}, // 9: body ->  sequence
     {305, 2}, // 10: sequence ->  statement sequence
     {305, 1}, // 11: sequence ->  statement
     {306, 5}, // 12: statement (MOVE) ->  MOVE expression TO VAR END
     {306, 2}, // 13: statement (END) ->  arithmetic END
     {306, 3}, // 14: statement (WRITE) ->  WRITE expression END
     {306, 6}, // 15: statement (WHILE) ->  WHILE logic END sequence ENDWHILE END
     {306, 4}, // 16: statement (READ) ->  READ TO VAR END
     {306, 6}, // 17: statement (IF) ->  IF logic END sequence ENDIF END
     {306, 9}, // 18: statement (IF) ->  IF logic END sequence ELSE END sequence ENDIF END
     {307, 1}, // 19: logic ->  expression
     {307, 3}, // 20: logic (EQUAL) ->  logic EQUAL logic
     {307, 3}, // 21: logic (OR) ->  logic OR logic
     {307, 3}, // 22: logic (AND) ->  logic AND logic
     {307, 2}, // 23: logic (NOT) ->  NOT logic
     {307, 4}, // 24: logic (SMALLER) ->  logic SMALLER EQUAL logic
     {307, 4}, // 25: logic (BIGGER) ->  logic BIGGER EQUAL logic
     {307, 3}, // 26: logic (SMALLER) ->  logic SMALLER logic
     {307, 3}, // 27: logic (BIGGER) ->  logic BIGGER logic
     {307, 3}, // 28: logic (OPEN) ->  OPEN logic CLOSE
     {308, 1}, // 29: expression (VAR) ->  VAR
     {308, 1}, // 30: expression (NUM) ->  NUM
     {308, 1}, // 31: expression (TRUE) ->  TRUE
     {308, 1}, // 32: expression (FALSE) ->  FALSE
     {309, 4}, // 33: arithmetic (SUBTRACT) ->  SUBTRACT expression FROM VAR
     {309, 4}, // 34: arithmetic (ADD) ->  ADD expression TO VAR
     {309, 4}, // 35: arithmetic (MULTIPLY) ->  MULTIPLY VAR BY expression
     {309, 4}, // 36: arithmetic (DIVIDE) ->  DIVIDE VAR BY expression
     {309, 6}, // 37: arithmetic (MOD) ->  MOD VAR BY expression TO VAR
     {310, 1}, // 38: start_$ ->  start
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { REQ_TOKEN}, { 3} },           
    { {       301}, { 1} }, // start  
    { {       257}, { 2} }, // PROGRAM
    { {         0}, { 0} },           
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {            2} }, 
    { {     _EOF_}, { PARSE_ACCEPT} }, 
    { {         0}, {            0} }, 
};

SR__ s_2[] =
{
    { { REQ_TOKEN}, { 2} },       
    { {       276}, { 3} }, // VAR
    { {         0}, { 0} },       
};

SR__ s_3[] =
{
    { { REQ_TOKEN}, { 2} },       
    { {       281}, { 4} }, // END
    { {         0}, { 0} },       
};

SR__ s_4[] =
{
    { { REQ_DEF}, { 17} },               
    { {     302}, {  5} }, // declaration
    { {     304}, {  6} }, // body       
    { {     258}, {  7} }, // DATA       
    { {     305}, {  8} }, // sequence   
    { {     306}, {  9} }, // statement  
    { {     271}, { 10} }, // MOVE       
    { {     309}, { 11} }, // arithmetic 
    { {     267}, { 12} }, // WRITE      
    { {     260}, { 13} }, // WHILE      
    { {     266}, { 14} }, // READ       
    { {     262}, { 15} }, // IF         
    { {     283}, { 16} }, // SUBTRACT   
    { {     282}, { 17} }, // ADD        
    { {     284}, { 18} }, // MULTIPLY   
    { {     285}, { 19} }, // DIVIDE     
    { {     286}, { 20} }, // MOD        
    { {       0}, { -8} },               
};

SR__ s_5[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -1} }, 
};

SR__ s_6[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -2} }, 
};

SR__ s_7[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       259}, { 21} }, // DDOT
    { {         0}, {  0} },        
};

SR__ s_8[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR__ s_9[] =
{
    { { REQ_DEF}, {  14} },              
    { {     305}, {  22} }, // sequence  
    { {     306}, {   9} }, // statement 
    { {     271}, {  10} }, // MOVE      
    { {     309}, {  11} }, // arithmetic
    { {     267}, {  12} }, // WRITE     
    { {     260}, {  13} }, // WHILE     
    { {     266}, {  14} }, // READ      
    { {     262}, {  15} }, // IF        
    { {     283}, {  16} }, // SUBTRACT  
    { {     282}, {  17} }, // ADD       
    { {     284}, {  18} }, // MULTIPLY  
    { {     285}, {  19} }, // DIVIDE    
    { {     286}, {  20} }, // MOD       
    { {       0}, { -11} },              
};

SR__ s_10[] =
{
    { { REQ_TOKEN}, {  6} },              
    { {       308}, { 23} }, // expression
    { {       276}, { 24} }, // VAR       
    { {       277}, { 25} }, // NUM       
    { {       278}, { 26} }, // TRUE      
    { {       279}, { 27} }, // FALSE     
    { {         0}, {  0} },              
};

SR__ s_11[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {       281}, { 28} }, // END
    { {         0}, {  0} },       
};

SR__ s_12[] =
{
    { { REQ_TOKEN}, {  6} },              
    { {       308}, { 29} }, // expression
    { {       276}, { 24} }, // VAR       
    { {       277}, { 25} }, // NUM       
    { {       278}, { 26} }, // TRUE      
    { {       279}, { 27} }, // FALSE     
    { {         0}, {  0} },              
};

SR__ s_13[] =
{
    { { REQ_TOKEN}, {  9} },              
    { {       307}, { 30} }, // logic     
    { {       308}, { 31} }, // expression
    { {       297}, { 32} }, // NOT       
    { {       272}, { 33} }, // OPEN      
    { {       276}, { 24} }, // VAR       
    { {       277}, { 25} }, // NUM       
    { {       278}, { 26} }, // TRUE      
    { {       279}, { 27} }, // FALSE     
    { {         0}, {  0} },              
};

SR__ s_14[] =
{
    { { REQ_TOKEN}, {  2} },      
    { {       268}, { 34} }, // TO
    { {         0}, {  0} },      
};

SR__ s_15[] =
{
    { { REQ_TOKEN}, {  9} },              
    { {       307}, { 35} }, // logic     
    { {       308}, { 31} }, // expression
    { {       297}, { 32} }, // NOT       
    { {       272}, { 33} }, // OPEN      
    { {       276}, { 24} }, // VAR       
    { {       277}, { 25} }, // NUM       
    { {       278}, { 26} }, // TRUE      
    { {       279}, { 27} }, // FALSE     
    { {         0}, {  0} },              
};

SR__ s_16[] =
{
    { { REQ_TOKEN}, {  6} },              
    { {       308}, { 36} }, // expression
    { {       276}, { 24} }, // VAR       
    { {       277}, { 25} }, // NUM       
    { {       278}, { 26} }, // TRUE      
    { {       279}, { 27} }, // FALSE     
    { {         0}, {  0} },              
};

SR__ s_17[] =
{
    { { REQ_TOKEN}, {  6} },              
    { {       308}, { 37} }, // expression
    { {       276}, { 24} }, // VAR       
    { {       277}, { 25} }, // NUM       
    { {       278}, { 26} }, // TRUE      
    { {       279}, { 27} }, // FALSE     
    { {         0}, {  0} },              
};

SR__ s_18[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {       276}, { 38} }, // VAR
    { {         0}, {  0} },       
};

SR__ s_19[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {       276}, { 39} }, // VAR
    { {         0}, {  0} },       
};

SR__ s_20[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {       276}, { 40} }, // VAR
    { {         0}, {  0} },       
};

SR__ s_21[] =
{
    { { REQ_TOKEN}, {  3} },                  
    { {       303}, { 41} }, // vardeclaration
    { {       276}, { 42} }, // VAR           
    { {         0}, {  0} },                  
};

SR__ s_22[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -10} }, 
};

SR__ s_23[] =
{
    { { REQ_TOKEN}, {  2} },      
    { {       268}, { 43} }, // TO
    { {         0}, {  0} },      
};

SR__ s_24[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -29} }, 
};

SR__ s_25[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -30} }, 
};

SR__ s_26[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -31} }, 
};

SR__ s_27[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -32} }, 
};

SR__ s_28[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_29[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {       281}, { 44} }, // END
    { {         0}, {  0} },       
};

SR__ s_30[] =
{
    { { REQ_TOKEN}, {  7} },           
    { {       281}, { 45} }, // END    
    { {       298}, { 46} }, // EQUAL  
    { {       295}, { 47} }, // OR     
    { {       296}, { 48} }, // AND    
    { {       299}, { 49} }, // SMALLER
    { {       300}, { 50} }, // BIGGER 
    { {         0}, {  0} },           
};

SR__ s_31[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -19} }, 
};

SR__ s_32[] =
{
    { { REQ_TOKEN}, {  9} },              
    { {       307}, { 51} }, // logic     
    { {       308}, { 31} }, // expression
    { {       297}, { 32} }, // NOT       
    { {       272}, { 33} }, // OPEN      
    { {       276}, { 24} }, // VAR       
    { {       277}, { 25} }, // NUM       
    { {       278}, { 26} }, // TRUE      
    { {       279}, { 27} }, // FALSE     
    { {         0}, {  0} },              
};

SR__ s_33[] =
{
    { { REQ_TOKEN}, {  9} },              
    { {       307}, { 52} }, // logic     
    { {       308}, { 31} }, // expression
    { {       297}, { 32} }, // NOT       
    { {       272}, { 33} }, // OPEN      
    { {       276}, { 24} }, // VAR       
    { {       277}, { 25} }, // NUM       
    { {       278}, { 26} }, // TRUE      
    { {       279}, { 27} }, // FALSE     
    { {         0}, {  0} },              
};

SR__ s_34[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {       276}, { 53} }, // VAR
    { {         0}, {  0} },       
};

SR__ s_35[] =
{
    { { REQ_TOKEN}, {  7} },           
    { {       281}, { 54} }, // END    
    { {       298}, { 46} }, // EQUAL  
    { {       295}, { 47} }, // OR     
    { {       296}, { 48} }, // AND    
    { {       299}, { 49} }, // SMALLER
    { {       300}, { 50} }, // BIGGER 
    { {         0}, {  0} },           
};

SR__ s_36[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       269}, { 55} }, // FROM
    { {         0}, {  0} },        
};

SR__ s_37[] =
{
    { { REQ_TOKEN}, {  2} },      
    { {       268}, { 56} }, // TO
    { {         0}, {  0} },      
};

SR__ s_38[] =
{
    { { REQ_TOKEN}, {  2} },      
    { {       270}, { 57} }, // BY
    { {         0}, {  0} },      
};

SR__ s_39[] =
{
    { { REQ_TOKEN}, {  2} },      
    { {       270}, { 58} }, // BY
    { {         0}, {  0} },      
};

SR__ s_40[] =
{
    { { REQ_TOKEN}, {  2} },      
    { {       270}, { 59} }, // BY
    { {         0}, {  0} },      
};

SR__ s_41[] =
{
    { { REQ_DEF}, { 15} },              
    { {     304}, { 60} }, // body      
    { {     305}, {  8} }, // sequence  
    { {     306}, {  9} }, // statement 
    { {     271}, { 10} }, // MOVE      
    { {     309}, { 11} }, // arithmetic
    { {     267}, { 12} }, // WRITE     
    { {     260}, { 13} }, // WHILE     
    { {     266}, { 14} }, // READ      
    { {     262}, { 15} }, // IF        
    { {     283}, { 16} }, // SUBTRACT  
    { {     282}, { 17} }, // ADD       
    { {     284}, { 18} }, // MULTIPLY  
    { {     285}, { 19} }, // DIVIDE    
    { {     286}, { 20} }, // MOD       
    { {       0}, { -8} },              
};

SR__ s_42[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       265}, { 61} }, // TYPE
    { {         0}, {  0} },        
};

SR__ s_43[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {       276}, { 62} }, // VAR
    { {         0}, {  0} },       
};

SR__ s_44[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_45[] =
{
    { { REQ_TOKEN}, { 14} },              
    { {       305}, { 63} }, // sequence  
    { {       306}, {  9} }, // statement 
    { {       271}, { 10} }, // MOVE      
    { {       309}, { 11} }, // arithmetic
    { {       267}, { 12} }, // WRITE     
    { {       260}, { 13} }, // WHILE     
    { {       266}, { 14} }, // READ      
    { {       262}, { 15} }, // IF        
    { {       283}, { 16} }, // SUBTRACT  
    { {       282}, { 17} }, // ADD       
    { {       284}, { 18} }, // MULTIPLY  
    { {       285}, { 19} }, // DIVIDE    
    { {       286}, { 20} }, // MOD       
    { {         0}, {  0} },              
};

SR__ s_46[] =
{
    { { REQ_TOKEN}, {  9} },              
    { {       307}, { 64} }, // logic     
    { {       308}, { 31} }, // expression
    { {       297}, { 32} }, // NOT       
    { {       272}, { 33} }, // OPEN      
    { {       276}, { 24} }, // VAR       
    { {       277}, { 25} }, // NUM       
    { {       278}, { 26} }, // TRUE      
    { {       279}, { 27} }, // FALSE     
    { {         0}, {  0} },              
};

SR__ s_47[] =
{
    { { REQ_TOKEN}, {  9} },              
    { {       307}, { 65} }, // logic     
    { {       308}, { 31} }, // expression
    { {       297}, { 32} }, // NOT       
    { {       272}, { 33} }, // OPEN      
    { {       276}, { 24} }, // VAR       
    { {       277}, { 25} }, // NUM       
    { {       278}, { 26} }, // TRUE      
    { {       279}, { 27} }, // FALSE     
    { {         0}, {  0} },              
};

SR__ s_48[] =
{
    { { REQ_TOKEN}, {  9} },              
    { {       307}, { 66} }, // logic     
    { {       308}, { 31} }, // expression
    { {       297}, { 32} }, // NOT       
    { {       272}, { 33} }, // OPEN      
    { {       276}, { 24} }, // VAR       
    { {       277}, { 25} }, // NUM       
    { {       278}, { 26} }, // TRUE      
    { {       279}, { 27} }, // FALSE     
    { {         0}, {  0} },              
};

SR__ s_49[] =
{
    { { REQ_TOKEN}, { 10} },              
    { {       298}, { 67} }, // EQUAL     
    { {       307}, { 68} }, // logic     
    { {       308}, { 31} }, // expression
    { {       297}, { 32} }, // NOT       
    { {       272}, { 33} }, // OPEN      
    { {       276}, { 24} }, // VAR       
    { {       277}, { 25} }, // NUM       
    { {       278}, { 26} }, // TRUE      
    { {       279}, { 27} }, // FALSE     
    { {         0}, {  0} },              
};

SR__ s_50[] =
{
    { { REQ_TOKEN}, { 10} },              
    { {       298}, { 69} }, // EQUAL     
    { {       307}, { 70} }, // logic     
    { {       308}, { 31} }, // expression
    { {       297}, { 32} }, // NOT       
    { {       272}, { 33} }, // OPEN      
    { {       276}, { 24} }, // VAR       
    { {       277}, { 25} }, // NUM       
    { {       278}, { 26} }, // TRUE      
    { {       279}, { 27} }, // FALSE     
    { {         0}, {  0} },              
};

SR__ s_51[] =
{
    { { REQ_DEF}, {   4} },           
    { {     298}, {  46} }, // EQUAL  
    { {     299}, {  49} }, // SMALLER
    { {     300}, {  50} }, // BIGGER 
    { {       0}, { -23} },           
};

SR__ s_52[] =
{
    { { REQ_TOKEN}, {  7} },           
    { {       273}, { 71} }, // CLOSE  
    { {       298}, { 46} }, // EQUAL  
    { {       295}, { 47} }, // OR     
    { {       296}, { 48} }, // AND    
    { {       299}, { 49} }, // SMALLER
    { {       300}, { 50} }, // BIGGER 
    { {         0}, {  0} },           
};

SR__ s_53[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {       281}, { 72} }, // END
    { {         0}, {  0} },       
};

SR__ s_54[] =
{
    { { REQ_TOKEN}, { 14} },              
    { {       305}, { 73} }, // sequence  
    { {       306}, {  9} }, // statement 
    { {       271}, { 10} }, // MOVE      
    { {       309}, { 11} }, // arithmetic
    { {       267}, { 12} }, // WRITE     
    { {       260}, { 13} }, // WHILE     
    { {       266}, { 14} }, // READ      
    { {       262}, { 15} }, // IF        
    { {       283}, { 16} }, // SUBTRACT  
    { {       282}, { 17} }, // ADD       
    { {       284}, { 18} }, // MULTIPLY  
    { {       285}, { 19} }, // DIVIDE    
    { {       286}, { 20} }, // MOD       
    { {         0}, {  0} },              
};

SR__ s_55[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {       276}, { 74} }, // VAR
    { {         0}, {  0} },       
};

SR__ s_56[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {       276}, { 75} }, // VAR
    { {         0}, {  0} },       
};

SR__ s_57[] =
{
    { { REQ_TOKEN}, {  6} },              
    { {       308}, { 76} }, // expression
    { {       276}, { 24} }, // VAR       
    { {       277}, { 25} }, // NUM       
    { {       278}, { 26} }, // TRUE      
    { {       279}, { 27} }, // FALSE     
    { {         0}, {  0} },              
};

SR__ s_58[] =
{
    { { REQ_TOKEN}, {  6} },              
    { {       308}, { 77} }, // expression
    { {       276}, { 24} }, // VAR       
    { {       277}, { 25} }, // NUM       
    { {       278}, { 26} }, // TRUE      
    { {       279}, { 27} }, // FALSE     
    { {         0}, {  0} },              
};

SR__ s_59[] =
{
    { { REQ_TOKEN}, {  6} },              
    { {       308}, { 78} }, // expression
    { {       276}, { 24} }, // VAR       
    { {       277}, { 25} }, // NUM       
    { {       278}, { 26} }, // TRUE      
    { {       279}, { 27} }, // FALSE     
    { {         0}, {  0} },              
};

SR__ s_60[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -3} }, 
};

SR__ s_61[] =
{
    { { REQ_TOKEN}, {  3} },        
    { {       274}, { 79} }, // INT 
    { {       275}, { 80} }, // BOOL
    { {         0}, {  0} },        
};

SR__ s_62[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {       281}, { 81} }, // END
    { {         0}, {  0} },       
};

SR__ s_63[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       261}, { 82} }, // ENDWHILE
    { {         0}, {  0} },            
};

SR__ s_64[] =
{
    { { REQ_DEF}, {   3} },           
    { {     299}, {  49} }, // SMALLER
    { {     300}, {  50} }, // BIGGER 
    { {       0}, { -20} },           
};

SR__ s_65[] =
{
    { { REQ_DEF}, {   5} },           
    { {     298}, {  46} }, // EQUAL  
    { {     296}, {  48} }, // AND    
    { {     299}, {  49} }, // SMALLER
    { {     300}, {  50} }, // BIGGER 
    { {       0}, { -21} },           
};

SR__ s_66[] =
{
    { { REQ_DEF}, {   4} },           
    { {     298}, {  46} }, // EQUAL  
    { {     299}, {  49} }, // SMALLER
    { {     300}, {  50} }, // BIGGER 
    { {       0}, { -22} },           
};

SR__ s_67[] =
{
    { { REQ_TOKEN}, {  9} },              
    { {       307}, { 83} }, // logic     
    { {       308}, { 31} }, // expression
    { {       297}, { 32} }, // NOT       
    { {       272}, { 33} }, // OPEN      
    { {       276}, { 24} }, // VAR       
    { {       277}, { 25} }, // NUM       
    { {       278}, { 26} }, // TRUE      
    { {       279}, { 27} }, // FALSE     
    { {         0}, {  0} },              
};

SR__ s_68[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -26} }, 
};

SR__ s_69[] =
{
    { { REQ_TOKEN}, {  9} },              
    { {       307}, { 84} }, // logic     
    { {       308}, { 31} }, // expression
    { {       297}, { 32} }, // NOT       
    { {       272}, { 33} }, // OPEN      
    { {       276}, { 24} }, // VAR       
    { {       277}, { 25} }, // NUM       
    { {       278}, { 26} }, // TRUE      
    { {       279}, { 27} }, // FALSE     
    { {         0}, {  0} },              
};

SR__ s_70[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -27} }, 
};

SR__ s_71[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -28} }, 
};

SR__ s_72[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -16} }, 
};

SR__ s_73[] =
{
    { { REQ_TOKEN}, {  3} },         
    { {       264}, { 85} }, // ENDIF
    { {       263}, { 86} }, // ELSE 
    { {         0}, {  0} },         
};

SR__ s_74[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -33} }, 
};

SR__ s_75[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -34} }, 
};

SR__ s_76[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -35} }, 
};

SR__ s_77[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -36} }, 
};

SR__ s_78[] =
{
    { { REQ_TOKEN}, {  2} },      
    { {       268}, { 87} }, // TO
    { {         0}, {  0} },      
};

SR__ s_79[] =
{
    { { REQ_TOKEN}, {  3} },             
    { {       280}, { 88} }, // SEPARATOR
    { {       281}, { 89} }, // END      
    { {         0}, {  0} },             
};

SR__ s_80[] =
{
    { { REQ_TOKEN}, {  3} },             
    { {       280}, { 90} }, // SEPARATOR
    { {       281}, { 91} }, // END      
    { {         0}, {  0} },             
};

SR__ s_81[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR__ s_82[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {       281}, { 92} }, // END
    { {         0}, {  0} },       
};

SR__ s_83[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -24} }, 
};

SR__ s_84[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -25} }, 
};

SR__ s_85[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {       281}, { 93} }, // END
    { {         0}, {  0} },       
};

SR__ s_86[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {       281}, { 94} }, // END
    { {         0}, {  0} },       
};

SR__ s_87[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {       276}, { 95} }, // VAR
    { {         0}, {  0} },       
};

SR__ s_88[] =
{
    { { REQ_TOKEN}, {  3} },                  
    { {       303}, { 96} }, // vardeclaration
    { {       276}, { 42} }, // VAR           
    { {         0}, {  0} },                  
};

SR__ s_89[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -6} }, 
};

SR__ s_90[] =
{
    { { REQ_TOKEN}, {  3} },                  
    { {       303}, { 97} }, // vardeclaration
    { {       276}, { 42} }, // VAR           
    { {         0}, {  0} },                  
};

SR__ s_91[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -7} }, 
};

SR__ s_92[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR__ s_93[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};

SR__ s_94[] =
{
    { { REQ_TOKEN}, { 14} },              
    { {       305}, { 98} }, // sequence  
    { {       306}, {  9} }, // statement 
    { {       271}, { 10} }, // MOVE      
    { {       309}, { 11} }, // arithmetic
    { {       267}, { 12} }, // WRITE     
    { {       260}, { 13} }, // WHILE     
    { {       266}, { 14} }, // READ      
    { {       262}, { 15} }, // IF        
    { {       283}, { 16} }, // SUBTRACT  
    { {       282}, { 17} }, // ADD       
    { {       284}, { 18} }, // MULTIPLY  
    { {       285}, { 19} }, // DIVIDE    
    { {       286}, { 20} }, // MOD       
    { {         0}, {  0} },              
};

SR__ s_95[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -37} }, 
};

SR__ s_96[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -4} }, 
};

SR__ s_97[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR__ s_98[] =
{
    { { REQ_TOKEN}, {  2} },         
    { {       264}, { 99} }, // ENDIF
    { {         0}, {  0} },         
};

SR__ s_99[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {       281}, { 100} }, // END
    { {         0}, {   0} },       
};

SR__ s_100[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,  s_83,  s_84,  s_85,  s_86,  s_87,  s_88,  s_89,
  s_90,  s_91,  s_92,  s_93,  s_94,  s_95,  s_96,  s_97,  s_98,  s_99,
  s_100,
};

} // anonymous namespace ends




// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

ParserBase::ParserBase()
:
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}


void ParserBase::setDebug(bool mode)
{
    d_actionCases__ = false;
    d_debug__ = mode;
}

void ParserBase::setDebug(DebugMode__ mode)
{
    d_actionCases__ = mode & ACTIONCASES;
    d_debug__ =       mode & ON;
}

void Parser::print__()
{
// $insert print
}

void ParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void ParserBase::push__(size_t state)
{
    size_t currentSize = d_stateStack__.size();
    if (static_cast<size_t>(d_stackIdx__ + 1) == currentSize)
    {
        size_t newSize = currentSize + STACK_EXPANSION__;
        d_stateStack__.resize(newSize);
        // $insert LTYPEresize
        d_locationStack__.resize(newSize);
        if (d_valueStack__.capacity() >= newSize)
            d_valueStack__.resize(newSize);
        else
        {
            std::vector<STYPE__> enlarged(newSize);
            for (size_t idx = 0; idx != currentSize; ++idx)
                enlarged[idx] = std::move(d_valueStack__[idx]);
            d_valueStack__.swap(enlarged);
        }
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    // $insert LTYPEpush
    *(d_lsp__ = &d_locationStack__[d_stackIdx__]) = d_loc__;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = std::move(d_val__);
}

void ParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = std::move(d_nextVal__);
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void ParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = std::move(d_val__);
    d_token__ = token;
}
     
void ParserBase::pop__(size_t count)
{
    if (d_stackIdx__ < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
    // $insert LTYPEpop
    d_lsp__ = &d_locationStack__[d_stackIdx__];
}

inline size_t ParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void Parser::executeAction(int production)
try
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

    switch (production)
    {
        // $insert actioncases
        
        case 1:
#line 54 "syntactic.y"
        {
         std::cout << ";start -> PROGRAM VAR END declaration" << std::endl;
         std::cout << ";Változó deklaráció: " << *d_vsp__[-2].szoveg << std::endl;
         if( szimbolumtabla.count(*d_vsp__[-2].szoveg) > 0 )
         {
         std::stringstream ss;
         ss << "Ujradeklaralt valtozo: " << *d_vsp__[-2].szoveg << ".\n"
         << "Korabbi deklaracio sora: " << szimbolumtabla[*d_vsp__[-2].szoveg].decl_row << std::endl;
         error( ss.str().c_str() );
         }
         szimbolumtabla[*d_vsp__[-2].szoveg] = var_data(
         d_loc__.first_line, natural
         );
         std::cout << std::string("") +
         "extern ki_elojeles_egesz\n" +
         "extern be_elojeles_egesz\n" +
         "extern ki_logikai\n" +
         "extern be_logikai\n" +
         "global main\n" +
         *d_vsp__[0].szoveg;
         }
        break;

        case 2:
#line 80 "syntactic.y"
        {
         std::cout << ";declaration -> body" << std::endl;
         std::stringstream ss;
         ss << std::string("") +
         "section .text\n" +
         "main:\n" +
         *d_vsp__[0].szoveg +
         "ret\n";
         d_val__.szoveg = new std::string(ss.str());
         delete d_vsp__[0].szoveg;
         }
        break;

        case 3:
#line 93 "syntactic.y"
        {
         std::cout << ";declaration -> DATA DDOT vardeclaration body" << std::endl;
         std::stringstream ss;
         ss << std::string("") +
         "section .bss\n" +
         d_vsp__[-1].instr_d->code +
         "section .text\n" +
         "main:\n" +
         *d_vsp__[0].szoveg +
         "ret\n";
         d_val__.szoveg = new std::string(ss.str());
         delete d_vsp__[-1].instr_d;
         delete d_vsp__[0].szoveg;
         }
        break;

        case 4:
#line 111 "syntactic.y"
        {
         std::cout << ";vardeclaration -> VAR TYPE INT SEPARATOR vardeclaration" << std::endl;
         std::cout << ";Változó deklaráció: " << *d_vsp__[-4].szoveg << std::endl;
         if( szimbolumtabla.count(*d_vsp__[-4].szoveg) > 0 )
         {
         std::stringstream ss;
         ss << "Ujradeklaralt valtozo: " << *d_vsp__[-4].szoveg << ".\n"
         << "Korabbi deklaracio sora: " << szimbolumtabla[*d_vsp__[-4].szoveg].decl_row << std::endl;
         error( ss.str().c_str() );
         }
         szimbolumtabla[*d_vsp__[-4].szoveg] = var_data(
         d_loc__.first_line, natural
         );
         instr_data* data = new instr_data(
         d_loc__.first_line,
         *d_vsp__[-4].szoveg +
         ": resb 4\n" +
         d_vsp__[0].instr_d->code
         );
         d_val__.instr_d = data;
         delete d_vsp__[-4].szoveg;
         delete d_vsp__[0].instr_d;
         }
        break;

        case 5:
#line 136 "syntactic.y"
        {
         std::cout << ";vardeclaration -> VAR TYPE BOOL SEPARATOR vardeclaration" << std::endl;
         std::cout << ";Változó deklaráció: " << *d_vsp__[-4].szoveg << std::endl;
         if( szimbolumtabla.count(*d_vsp__[-4].szoveg) > 0 )
         {
         std::stringstream ss;
         ss << "Ujradeklaralt valtozo: " << *d_vsp__[-4].szoveg << ".\n"
         << "Korabbi deklaracio sora: " << szimbolumtabla[*d_vsp__[-4].szoveg].decl_row << std::endl;
         error( ss.str().c_str() );
         }
         szimbolumtabla[*d_vsp__[-4].szoveg] = var_data(
         d_loc__.first_line, boolean
         );
         instr_data* data = new instr_data(
         d_loc__.first_line,
         *d_vsp__[-4].szoveg +
         ": resb 1\n" +
         d_vsp__[0].instr_d->code
         );
         d_val__.instr_d = data;
         delete d_vsp__[-4].szoveg;
         delete d_vsp__[0].instr_d;
         }
        break;

        case 6:
#line 161 "syntactic.y"
        {
         std::cout << ";vardeclaration -> VAR TYPE INT END" << std::endl;
         std::cout << ";Változó deklaráció: " << *d_vsp__[-3].szoveg << std::endl;
         if( szimbolumtabla.count(*d_vsp__[-3].szoveg) > 0 )
         {
         std::stringstream ss;
         ss << "Ujradeklaralt valtozo: " << *d_vsp__[-3].szoveg << ".\n"
         << "Korabbi deklaracio sora: " << szimbolumtabla[*d_vsp__[-3].szoveg].decl_row << std::endl;
         error( ss.str().c_str() );
         }
         szimbolumtabla[*d_vsp__[-3].szoveg] = var_data(
         d_loc__.first_line, natural
         );
         instr_data* data = new instr_data(
         d_loc__.first_line,
         *d_vsp__[-3].szoveg +
         ": resb 4\n"
         );
         d_val__.instr_d = data;
         delete d_vsp__[-3].szoveg;
         }
        break;

        case 7:
#line 185 "syntactic.y"
        {
         std::cout << ";vardeclaration -> VAR TYPE BOOL END" << std::endl;
         std::cout << ";Változó deklaráció: " << *d_vsp__[-3].szoveg << std::endl;
         if( szimbolumtabla.count(*d_vsp__[-3].szoveg) > 0 )
         {
         std::stringstream ss;
         ss << "Ujradeklaralt valtozo: " << *d_vsp__[-3].szoveg << ".\n"
         << "Korabbi deklaracio sora: " << szimbolumtabla[*d_vsp__[-3].szoveg].decl_row << std::endl;
         error( ss.str().c_str() );
         }
         szimbolumtabla[*d_vsp__[-3].szoveg] = var_data(
         d_loc__.first_line, boolean
         );
         instr_data* data = new instr_data(
         d_loc__.first_line,
         *d_vsp__[-3].szoveg +
         ": resb 1\n"
         );
         d_val__.instr_d = data;
         delete d_vsp__[-3].szoveg;
         }
        break;

        case 8:
#line 211 "syntactic.y"
        {
         std::cout << ";body -> empty" << std::endl;
         d_val__.szoveg = new std::string("");
         }
        break;

        case 9:
#line 217 "syntactic.y"
        {
         std::cout << ";body -> sequence" << std::endl;
         d_val__.szoveg = new std::string(*d_vsp__[0].szoveg);
         }
        break;

        case 10:
#line 225 "syntactic.y"
        {
         std::cout << ";sequence -> statement sequence" << std::endl;
         d_val__.szoveg = new std::string(
         *d_vsp__[-1].szoveg +
         *d_vsp__[0].szoveg
         );
         }
        break;

        case 11:
#line 234 "syntactic.y"
        {
         std::cout << ";sequence -> statement" << std::endl;
         d_val__.szoveg = d_vsp__[0].szoveg;
         }
        break;

        case 12:
#line 242 "syntactic.y"
        {
         std::cout << ";sequence -> MOVE expression TO VAR END" << std::endl;
         if( szimbolumtabla.count(*d_vsp__[-1].szoveg) == 0 )
         {
         std::stringstream ss;
         ss << "Nem deklaralt valtozo: " << *d_vsp__[-1].szoveg << ".\n" << std::endl;
         error( ss.str().c_str() );
         }
         if(d_vsp__[-3].expr_d->var_type != szimbolumtabla[*d_vsp__[-1].szoveg].var_type)
         {
         error("Tipushibas ertekadas.\n");
         }
         d_val__.szoveg = new std::string(std::string("") +
         d_vsp__[-3].expr_d->code +
         "mov [" + *d_vsp__[-1].szoveg + "], eax\n");
         delete d_vsp__[-1].szoveg;
         delete d_vsp__[-3].expr_d;
         }
        break;

        case 13:
#line 265 "syntactic.y"
        {
         std::cout << ";sequence -> arithmetic END" << std::endl;
         d_val__.szoveg = d_vsp__[-1].szoveg;
         }
        break;

        case 14:
#line 271 "syntactic.y"
        {
         std::cout << ";sequence -> WRITE expression END" << std::endl;
         if(d_vsp__[-1].expr_d->var_type == natural)
         {
         d_val__.szoveg = new std::string(std::string("") +
         d_vsp__[-1].expr_d->code +
         "push eax\n" + 
         "call ki_elojeles_egesz\n" +
         "add esp, 4\n"
         );
         }
         else if(d_vsp__[-1].expr_d->var_type == boolean)
         {
         d_val__.szoveg = new std::string(std::string("") +
         d_vsp__[-1].expr_d->code +
         "push eax\n" + 
         "call ki_logikai\n" +
         "add esp, 4\n"
         );
         } 
         }
        break;

        case 15:
#line 294 "syntactic.y"
        {
         std::cout << ";sequence -> WHILE logic END sequence ENDWHILE" << std::endl;
         if(d_vsp__[-4].expr_d->var_type != boolean)
         {
         error("Tipushibas IF.\n");
         } 
         std::string label = std::string("cikluseleje") + std::to_string(d_loc__.first_line);
         std::string labelend = std::string("ciklusvege") + std::to_string(d_loc__.first_line);
         d_val__.szoveg = new std::string(std::string("") +
         label + ":\n" +
         d_vsp__[-4].expr_d->code +
         "cmp al, 1\n" + 
         "jne near " + labelend + "\n" +
         *d_vsp__[-2].szoveg +
         "jmp " + label + "\n" +
         labelend + ":\n"
         );
         delete d_vsp__[-4].expr_d;
         }
        break;

        case 16:
#line 316 "syntactic.y"
        {
         std::cout << ";sequence -> READ TO VAR END" << std::endl;
         if( szimbolumtabla.count(*d_vsp__[-1].szoveg) == 0 )
         {
         std::stringstream ss;
         ss << "Nem deklaralt valtozo: " << *d_vsp__[-1].szoveg << ".\n" << std::endl;
         error( ss.str().c_str() );
         }
         if(szimbolumtabla[*d_vsp__[-1].szoveg].var_type == natural)
         {
         d_val__.szoveg = new std::string(std::string("") +
         "call be_elojeles_egesz\n" +
         "mov [" + *d_vsp__[-1].szoveg + "], eax\n"
         );
         }
         else if(szimbolumtabla[*d_vsp__[-1].szoveg].var_type == boolean)
         {
         d_val__.szoveg = new std::string(std::string("") +
         "call be_logikai\n" +
         "mov [" + *d_vsp__[-1].szoveg + "], eax\n"
         );
         }
         }
        break;

        case 17:
#line 341 "syntactic.y"
        {
         std::cout << ";sequence -> IF logic END sequence ENDIF END" << std::endl;
         if(d_vsp__[-4].expr_d->var_type != boolean)
         {
         error("Tipushibas IF.\n");
         } 
         std::string label = std::string("labelegyagu") + std::to_string(d_loc__.first_line);
         d_val__.szoveg = new std::string(std::string("") +
         d_vsp__[-4].expr_d->code +
         "cmp al, 1\n" +
         "jne near " + label + "\n" +
         *d_vsp__[-2].szoveg +
         label + ":\n"
         );
         delete d_vsp__[-4].expr_d;
         }
        break;

        case 18:
#line 359 "syntactic.y"
        {
         std::cout << ";sequence -> IF logic END sequence ELSE END sequence ENDIF END" << std::endl;
         if(d_vsp__[-7].expr_d->var_type != boolean)
         {
         error("Tipushibas IF.\n");
         } 
         std::string label = std::string("labelketto") + std::to_string(d_loc__.first_line);
         std::string labelend = std::string("labelkettoend") + std::to_string(d_loc__.first_line);
         d_val__.szoveg = new std::string(std::string("") +
         d_vsp__[-7].expr_d->code +
         "cmp al, 1\n" +
         "jne near " + label + "\n" +
         *d_vsp__[-5].szoveg +
         "jmp " + labelend + "\n" +
         label + ":\n" +
         *d_vsp__[-2].szoveg +
         labelend + ":\n"
         );
         delete d_vsp__[-7].expr_d;
         }
        break;

        case 19:
#line 384 "syntactic.y"
        {
         std::cout << ";logic -> expression" << std::endl; 
         
         d_val__.expr_d = new expr_data(d_vsp__[0].expr_d->row,
         d_vsp__[0].expr_d->var_type,
         std::string("") + 
         d_vsp__[0].expr_d->code
         );
         }
        break;

        case 20:
#line 395 "syntactic.y"
        {
         std::cout << ";logic -> logic EQUAL logic" << std::endl; 
         if(d_vsp__[-2].expr_d->var_type != d_vsp__[0].expr_d->var_type)
         {
         error("Tipushibas logika.\n");
         } 
         std::string label = std::string("labelegyenlo") + std::to_string(d_loc__.first_line);
         std::string labelend = std::string("labelegyenloend") + std::to_string(d_loc__.first_line);
         d_val__.expr_d = new expr_data(d_loc__.first_line,
         boolean,
         std::string("") + 
         d_vsp__[0].expr_d->code + 
         "push eax\n" +
         d_vsp__[-2].expr_d->code +
         "pop ebx\n" +
         "cmp eax, ebx\n" +
         "je " + label + "\n" +
         "mov al, 0\n" +
         "jmp " + labelend + "\n" +
         label + ":\n" +
         "mov al, 1\n" +
         labelend + ":\n"
         );
         delete d_vsp__[-2].expr_d;
         delete d_vsp__[0].expr_d;
         }
        break;

        case 21:
#line 423 "syntactic.y"
        {
         std::cout << ";logic -> logic OR logic" << std::endl;
         if(!(d_vsp__[-2].expr_d->var_type == d_vsp__[0].expr_d->var_type && d_vsp__[-2].expr_d->var_type == boolean))
         {
         error("Tipushibas logika.\n");
         } 
         d_val__.expr_d = new expr_data(d_loc__.first_line,
         boolean,
         std::string("") + 
         d_vsp__[0].expr_d->code + 
         "push ax\n" +
         d_vsp__[-2].expr_d->code +
         "pop bx\n" +
         "or al, bl\n"
         );
         delete d_vsp__[-2].expr_d;
         delete d_vsp__[0].expr_d;
         }
        break;

        case 22:
#line 443 "syntactic.y"
        {
         std::cout << ";logic -> logic AND logic" << std::endl;
         if(!(d_vsp__[-2].expr_d->var_type == d_vsp__[0].expr_d->var_type && d_vsp__[-2].expr_d->var_type == boolean))
         {
         error("Tipushibas logika.\n");
         } 
         d_val__.expr_d = new expr_data(d_loc__.first_line,
         boolean,
         std::string("") + 
         d_vsp__[0].expr_d->code + 
         "push ax\n" +
         d_vsp__[-2].expr_d->code +
         "pop bx\n" +
         "and al, bl\n"
         );
         delete d_vsp__[-2].expr_d;
         delete d_vsp__[0].expr_d;
         }
        break;

        case 23:
#line 463 "syntactic.y"
        {
         std::cout << ";logic -> NOT logic" << std::endl;
         
         if(d_vsp__[0].expr_d->var_type != boolean)
         {
         error("Tipushibas logika.\n");
         } 
         std::string label = std::string("labelnot") + std::to_string(d_loc__.first_line);
         std::string labelend = std::string("labelnotend") + std::to_string(d_loc__.first_line);
         d_val__.expr_d = new expr_data(d_loc__.first_line,
         boolean,
         std::string("") + 
         d_vsp__[0].expr_d->code + 
         "not eax\n"
         );
         
         delete d_vsp__[0].expr_d;
         }
        break;

        case 24:
#line 484 "syntactic.y"
        {
         std::cout << ";logic -> logic SMALLER EQUAL logic" << std::endl;
         if(!(d_vsp__[-3].expr_d->var_type == d_vsp__[0].expr_d->var_type && d_vsp__[-3].expr_d->var_type == natural))
         {
         error("Tipushibas logika.\n");
         } 
         std::string label = std::string("labelsmallerequal") + std::to_string(d_loc__.first_line);
         std::string labelend = std::string("labelsmallerequalend") + std::to_string(d_loc__.first_line);
         d_val__.expr_d = new expr_data(d_loc__.first_line,
         boolean,
         std::string("") + 
         d_vsp__[0].expr_d->code + 
         "push eax\n" +
         d_vsp__[-3].expr_d->code +
         "pop ebx\n" +
         "cmp eax, ebx\n" +
         "jbe " + label + "\n" +
         "mov al, 0\n" +
         "jmp " + labelend + "\n" +
         label + ":\n" +
         "mov al, 1\n" +
         labelend + ":\n"
         );
         delete d_vsp__[-3].expr_d;
         delete d_vsp__[0].expr_d;
         }
        break;

        case 25:
#line 512 "syntactic.y"
        {
         std::cout << ";logic -> logic BIGGER EQUAL logic" << std::endl;
         if(!(d_vsp__[-3].expr_d->var_type == d_vsp__[0].expr_d->var_type && d_vsp__[-3].expr_d->var_type == natural))
         {
         error("Tipushibas logika.\n");
         } 
         std::string label = std::string("labelbiggerequal") + std::to_string(d_loc__.first_line);
         std::string labelend = std::string("labelbiggerequalend") + std::to_string(d_loc__.first_line);
         d_val__.expr_d = new expr_data(d_loc__.first_line,
         boolean,
         std::string("") + 
         d_vsp__[0].expr_d->code + 
         "push eax\n" +
         d_vsp__[-3].expr_d->code +
         "pop ebx\n" +
         "cmp eax, ebx\n" +
         "jae " + label + "\n" +
         "mov al, 0\n" +
         "jmp " + labelend + "\n" +
         label + ":\n" +
         "mov al, 1\n" +
         labelend + ":\n"
         );
         delete d_vsp__[-3].expr_d;
         delete d_vsp__[0].expr_d;
         }
        break;

        case 26:
#line 540 "syntactic.y"
        {
         std::cout << ";logic -> logic SMALLER logic" << std::endl;
         if(!(d_vsp__[-2].expr_d->var_type == d_vsp__[0].expr_d->var_type && d_vsp__[-2].expr_d->var_type == natural))
         {
         error("Tipushibas logika.\n");
         } 
         std::string label = std::string("labelsmaller") + std::to_string(d_loc__.first_line);
         std::string labelend = std::string("labelsmallerend") + std::to_string(d_loc__.first_line);
         d_val__.expr_d = new expr_data(d_loc__.first_line,
         boolean,
         std::string("") + 
         d_vsp__[0].expr_d->code + 
         "push eax\n" +
         d_vsp__[-2].expr_d->code +
         "pop ebx\n" +
         "cmp eax, ebx\n" +
         "jb " + label + "\n" +
         "mov al, 0\n" +
         "jmp " + labelend + "\n" +
         label + ":\n" +
         "mov al, 1\n" +
         labelend + ":\n"
         );
         delete d_vsp__[-2].expr_d;
         delete d_vsp__[0].expr_d;
         }
        break;

        case 27:
#line 568 "syntactic.y"
        {
         std::cout << ";logic -> logic BIGGER logic" << std::endl;
         if(!(d_vsp__[-2].expr_d->var_type == d_vsp__[0].expr_d->var_type && d_vsp__[-2].expr_d->var_type == natural))
         {
         error("Tipushibas logika.\n");
         } 
         std::string label = std::string("labelbigger") + std::to_string(d_loc__.first_line);
         std::string labelend = std::string("labelbiggerend") + std::to_string(d_loc__.first_line);
         d_val__.expr_d = new expr_data(d_loc__.first_line,
         boolean,
         std::string("") + 
         d_vsp__[0].expr_d->code + 
         "push eax\n" +
         d_vsp__[-2].expr_d->code +
         "pop ebx\n" +
         "cmp eax, ebx\n" +
         "ja " + label + "\n" +
         "mov al, 0\n" +
         "jmp " + labelend + "\n" +
         label + ":\n" +
         "mov al, 1\n" +
         labelend + ":\n"
         );
         delete d_vsp__[-2].expr_d;
         delete d_vsp__[0].expr_d;
         }
        break;

        case 28:
#line 596 "syntactic.y"
        {
         std::cout << ";logic -> OPEN logic CLOSE" << std::endl;
         delete d_vsp__[-1].expr_d;
         d_val__.expr_d = new expr_data(d_loc__.first_line,
         d_vsp__[-1].expr_d->var_type,
         std::string("") + 
         d_vsp__[-1].expr_d->code
         );
         }
        break;

        case 29:
#line 610 "syntactic.y"
        {
         std::cout << ";expression -> VAR" << std::endl;
         if( szimbolumtabla.count(*d_vsp__[0].szoveg) == 0 )
         {
         std::stringstream ss;
         ss << "Nem deklaralt valtozo: " << *d_vsp__[0].szoveg << ".\n" << std::endl;
         error( ss.str().c_str() );
         }
         d_val__.expr_d = new expr_data(d_loc__.first_line,
         szimbolumtabla[*d_vsp__[0].szoveg].var_type,
         std::string("") + 
         "mov eax, [" + *d_vsp__[0].szoveg + "]\n"
         );
         delete d_vsp__[0].szoveg;
         }
        break;

        case 30:
#line 629 "syntactic.y"
        {
         std::cout << ";expression -> NUM" << std::endl;
         
         d_val__.expr_d = new expr_data(d_loc__.first_line,
         natural,
         std::string("") + 
         "mov eax, " + *d_vsp__[0].szoveg + "\n"
         );
         }
        break;

        case 31:
#line 640 "syntactic.y"
        {
         std::cout << ";expression -> TRUE" << std::endl;
         
         d_val__.expr_d = new expr_data(d_loc__.first_line,
         boolean,
         std::string("") + 
         "mov eax, 1\n"
         );
         }
        break;

        case 32:
#line 651 "syntactic.y"
        {
         std::cout << ";expression -> FALSE" << std::endl;
         
         d_val__.expr_d = new expr_data(d_loc__.first_line,
         boolean,
         std::string("") + 
         "mov eax, 0\n"
         );
         }
        break;

        case 33:
#line 664 "syntactic.y"
        {
         std::cout << ";arithmetic -> SUBTRACT expression FROM VAR" << std::endl;
         if( szimbolumtabla.count(*d_vsp__[0].szoveg) == 0 )
         {
         
         std::stringstream ss;
         ss << "Nem deklaralt valtozo: " << *d_vsp__[0].szoveg << ".\n" << std::endl;
         error( ss.str().c_str() );
         } 
         
         if(d_vsp__[-2].expr_d->var_type != szimbolumtabla[*d_vsp__[0].szoveg].var_type)
         {
         error("Tipushibas ertekadas.\n");
         } 
         d_val__.szoveg = new std::string(std::string("") + 
         d_vsp__[-2].expr_d->code +
         "push eax\n" + 
         "mov eax, [" + *d_vsp__[0].szoveg + "]\n" + 
         "pop ebx\n" +
         "sub eax, ebx\n" +
         "mov [" + *d_vsp__[0].szoveg + "], eax\n" 
         );
         delete d_vsp__[-2].expr_d;
         delete d_vsp__[0].szoveg; 
         }
        break;

        case 34:
#line 691 "syntactic.y"
        {
         std::cout << ";arithmetic -> ADD expression TO VAR END sequence" << std::endl;
         if( szimbolumtabla.count(*d_vsp__[0].szoveg) == 0 )
         {
         
         std::stringstream ss;
         ss << "Nem deklaralt valtozo: " << *d_vsp__[0].szoveg << ".\n" << std::endl;
         error( ss.str().c_str() );
         } 
         
         if(d_vsp__[-2].expr_d->var_type != szimbolumtabla[*d_vsp__[0].szoveg].var_type)
         {
         error("Tipushibas ertekadas.\n");
         } 
         d_val__.szoveg = new std::string(std::string("") + 
         d_vsp__[-2].expr_d->code +
         "push eax\n" + 
         "mov eax, [" + *d_vsp__[0].szoveg + "]\n" + 
         "pop ebx\n" +
         "add eax, ebx\n" +
         "mov [" + *d_vsp__[0].szoveg + "], eax\n" 
         );
         delete d_vsp__[-2].expr_d;
         delete d_vsp__[0].szoveg; 
         }
        break;

        case 35:
#line 720 "syntactic.y"
        {
         std::cout << ";arithmetic -> MULTIPLY VAR BY expression" << std::endl;
         if( szimbolumtabla.count(*d_vsp__[-2].szoveg) == 0 )
         {
         
         std::stringstream ss;
         ss << "Nem deklaralt valtozo: " << *d_vsp__[-2].szoveg << ".\n" << std::endl;
         error( ss.str().c_str() );
         } 
         
         if(szimbolumtabla[*d_vsp__[-2].szoveg].var_type != d_vsp__[0].expr_d->var_type)
         {
         error("Tipushibas ertekadas.\n");
         } 
         d_val__.szoveg = new std::string(std::string("") + 
         d_vsp__[0].expr_d->code +
         "mul dword [" + *d_vsp__[-2].szoveg + "]\n" + 
         "mov [" + *d_vsp__[-2].szoveg + "], eax\n" 
         );
         delete d_vsp__[-2].szoveg;
         delete d_vsp__[0].expr_d; 
         }
        break;

        case 36:
#line 744 "syntactic.y"
        {
         std::cout << ";arithmetic -> DIVIDE VAR BY expression" << std::endl;
         if( szimbolumtabla.count(*d_vsp__[-2].szoveg) == 0 )
         {
         
         std::stringstream ss;
         ss << "Nem deklaralt valtozo: " << *d_vsp__[-2].szoveg << ".\n" << std::endl;
         error( ss.str().c_str() );
         } 
         
         if(szimbolumtabla[*d_vsp__[-2].szoveg].var_type != d_vsp__[0].expr_d->var_type)
         {
         error("Tipushibas ertekadas.\n");
         } 
         d_val__.szoveg = new std::string(std::string("") + 
         d_vsp__[0].expr_d->code +
         "push eax\n" + 
         "mov eax, [" + *d_vsp__[-2].szoveg + "]\n" + 
         "pop ebx\n" +
         "sub eax, ebx\n" +
         "mov [" + *d_vsp__[-2].szoveg + "], eax\n" 
         );
         delete d_vsp__[-2].szoveg;
         delete d_vsp__[0].expr_d; 
         }
        break;

        case 37:
#line 771 "syntactic.y"
        {
         std::cout << ";arithmetic -> MOD VAR BY expression TO VAR" << std::endl;
         if( szimbolumtabla.count(*d_vsp__[-4].szoveg) == 0)
         {
         
         std::stringstream ss;
         ss << "Nem deklaralt valtozo: " << *d_vsp__[-4].szoveg << ".\n" << std::endl;
         error( ss.str().c_str() );
         } 
         if( szimbolumtabla.count(*d_vsp__[0].szoveg) == 0)
         {
         
         std::stringstream ss;
         ss << "Nem deklaralt valtozo: " << *d_vsp__[0].szoveg << ".\n" << std::endl;
         error( ss.str().c_str() );
         } 
         
         if(!(szimbolumtabla[*d_vsp__[-4].szoveg].var_type == d_vsp__[-2].expr_d->var_type && d_vsp__[-2].expr_d->var_type == szimbolumtabla[*d_vsp__[0].szoveg].var_type))
         {
         error("Tipushibas ertekadas.\n");
         } 
         d_val__.szoveg = new std::string(std::string("") + 
         d_vsp__[-2].expr_d->code +
         "mov edx, 0\n" +
         "mov ebx, [" + *d_vsp__[-4].szoveg + "]\n" + 
         "div ebx\n" +
         "mov [" + *d_vsp__[0].szoveg + "], eax\n"
         );
         delete d_vsp__[-4].szoveg;
         delete d_vsp__[-2].expr_d; 
         delete d_vsp__[0].szoveg; 
         }
        break;

    }
}
catch (std::exception const &exc)
{
    exceptionHandler__(exc);
}

inline void ParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void Parser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int Parser::lookup(bool recovery)
{
// $insert threading
    SR__ *sr = s_state[d_state__];          // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;            // sentinel-index in the SR__ array
    
    SR__ *lastElementPtr = sr + lastIdx;
    lastElementPtr->d_token = d_token__;    // set search-token
    
    SR__ *elementPtr = sr + 1;              // start the search at s_xx[1]
    while (elementPtr->d_token != d_token__)
        ++elementPtr;
    

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
            return elementPtr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;


    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void Parser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }


    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();

                if (gotToken)
                {

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int Parser::parse()
try 
{
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    return retValue;
}



